# Site settings
title:          "keithbuhler.com"
author:         "Keith Buhler"
email:          "keithedbuhler@gmail.com"
description:    "The personal website of Keith Buhler, philosopher and author"
baseurl:        ""
url:            "http://www.keithbuhler.com"
paginate:       5
paginate_path:  "/page:num"


# lunr_search:
#   excludes: [sitemap.xml,index.html,search,archive,papers,share,teaching]

# Build settings
markdown:       kramdown
markdown_ext:   markdown,mkdown,mkdn,mkd,md
encoding:       utf-8



collections:
  papers:
    output: true
  teaching:
    output: true
  presentations:
    output: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "posts" # overrides previous default layout
  -
    scope:
      path: "presentations"
      type: "presentations"
    values:
      layout: "presentation"
