# Site settings
title:          "keithbuhler.com"
author:         "Keith Buhler"
email:          "keithedbuhler@gmail.com"
description:    "The personal website of Keith Buhler, philosopher and author"
baseurl:        ""
url:            "http://www.keithbuhler.com"
paginate:       30
paginate_path:  "/posts:num"

# lunr_search:
#   excludes: [sitemap.xml,index.html,search,archive,papers,share,teaching]

# Build settings
markdown:       kramdown
markdown_ext:   markdown,mkdown,mkdn,mkd,md
encoding:       utf-8
`

# Owner/author information
owner:
  name:           Keith Buhler
  avatar:         keithbuhlerface.jpg
  bio:            Philosopher, classical educator, writer
  email:          keithbuhler@gmail.com

  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Hossain Mohammad Faysal is an Electrical Engineer and a Mathematician based in Doha, Qatar. His interests are anything that&#8217;s related to math, from math itself to programming languages to music to physics to engineering to philosophy.
  # Social networking links used in footer. Update and remove as you like.
  twitter:        keith_buhler
  facebook:       keithedbuhler
  github:         keithbuhler
  google_plus:    https://plus.google.com/u/0/102602916593522619858
  instagram:      n/a
  flickr:         n/a
  tumblr:         n/a


# Timezone
timezone:     America/New_York   



# Links to include in footer navigation

# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: <i class="icon-book"></i> Documentation
    url: /documentation
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: Buhler who?
    url: /hossain-mohd-faysal

# Plugins

gems: 
  -jekyll-paginate
  -jekyll-sitemap

    
collections:
  papers:
    output: true
  teaching:
    output: true
  presentations:
    output: true

defaults:
  -
    scope:
      path: "" # empty string for all files
      values:
      layout: "default"
      read_time: false
      comments: true
      share: true
      related: true
  -
    scope:
      path: "posts"
      type: ""
    values:
      layout: "posts" # overrides previous default layout
  -
    scope:
      path: "presentations"
      type: "presentations"
    values:
      layout: "presentation"
      

